# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ccmslam_msgs/PC.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class PC(genpy.Message):
  _md5sum = "bcd02d77df99fd4888c5c5f0c39553bc"
  _type = "ccmslam_msgs/PC"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 mDepth
float64 mx
float64 my
uint8 mblue
uint8 mgreen
uint8 mred"""
  __slots__ = ['mDepth','mx','my','mblue','mgreen','mred']
  _slot_types = ['float64','float64','float64','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       mDepth,mx,my,mblue,mgreen,mred

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PC, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.mDepth is None:
        self.mDepth = 0.
      if self.mx is None:
        self.mx = 0.
      if self.my is None:
        self.my = 0.
      if self.mblue is None:
        self.mblue = 0
      if self.mgreen is None:
        self.mgreen = 0
      if self.mred is None:
        self.mred = 0
    else:
      self.mDepth = 0.
      self.mx = 0.
      self.my = 0.
      self.mblue = 0
      self.mgreen = 0
      self.mred = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3d3B().pack(_x.mDepth, _x.mx, _x.my, _x.mblue, _x.mgreen, _x.mred))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 27
      (_x.mDepth, _x.mx, _x.my, _x.mblue, _x.mgreen, _x.mred,) = _get_struct_3d3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3d3B().pack(_x.mDepth, _x.mx, _x.my, _x.mblue, _x.mgreen, _x.mred))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 27
      (_x.mDepth, _x.mx, _x.my, _x.mblue, _x.mgreen, _x.mred,) = _get_struct_3d3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d3B = None
def _get_struct_3d3B():
    global _struct_3d3B
    if _struct_3d3B is None:
        _struct_3d3B = struct.Struct("<3d3B")
    return _struct_3d3B
