// Generated by gencpp from file ccmslam_msgs/right.msg
// DO NOT EDIT!


#ifndef CCMSLAM_MSGS_MESSAGE_RIGHT_H
#define CCMSLAM_MSGS_MESSAGE_RIGHT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ccmslam_msgs
{
template <class ContainerAllocator>
struct right_
{
  typedef right_<ContainerAllocator> Type;

  right_()
    : mvuRight(0.0)  {
    }
  right_(const ContainerAllocator& _alloc)
    : mvuRight(0.0)  {
  (void)_alloc;
    }



   typedef float _mvuRight_type;
  _mvuRight_type mvuRight;





  typedef boost::shared_ptr< ::ccmslam_msgs::right_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ccmslam_msgs::right_<ContainerAllocator> const> ConstPtr;

}; // struct right_

typedef ::ccmslam_msgs::right_<std::allocator<void> > right;

typedef boost::shared_ptr< ::ccmslam_msgs::right > rightPtr;
typedef boost::shared_ptr< ::ccmslam_msgs::right const> rightConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ccmslam_msgs::right_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ccmslam_msgs::right_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ccmslam_msgs::right_<ContainerAllocator1> & lhs, const ::ccmslam_msgs::right_<ContainerAllocator2> & rhs)
{
  return lhs.mvuRight == rhs.mvuRight;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ccmslam_msgs::right_<ContainerAllocator1> & lhs, const ::ccmslam_msgs::right_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ccmslam_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ccmslam_msgs::right_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ccmslam_msgs::right_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ccmslam_msgs::right_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ccmslam_msgs::right_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ccmslam_msgs::right_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ccmslam_msgs::right_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ccmslam_msgs::right_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18e1f68062c1d4bb45359a23f5776613";
  }

  static const char* value(const ::ccmslam_msgs::right_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18e1f68062c1d4bbULL;
  static const uint64_t static_value2 = 0x45359a23f5776613ULL;
};

template<class ContainerAllocator>
struct DataType< ::ccmslam_msgs::right_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ccmslam_msgs/right";
  }

  static const char* value(const ::ccmslam_msgs::right_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ccmslam_msgs::right_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 mvuRight\n"
;
  }

  static const char* value(const ::ccmslam_msgs::right_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ccmslam_msgs::right_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mvuRight);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct right_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ccmslam_msgs::right_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ccmslam_msgs::right_<ContainerAllocator>& v)
  {
    s << indent << "mvuRight: ";
    Printer<float>::stream(s, indent + "  ", v.mvuRight);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CCMSLAM_MSGS_MESSAGE_RIGHT_H
